[build]
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/translate"
  to = "/.netlify/functions/translate"
  status = 200

